apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.5.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          - name: SERVER_BASEPATH
            value: '/kibana'
          - name: SERVER_REWRITEBASEPATH
            value: 'true'
          #- name: SERVER_PUBLICBASEURL
          #  value: 'http://computervision.eastus.cloudapp.azure.com/kibana'            
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
    name: kibana
    namespace: default
spec:
    selector:
        app: kibana
    type: ClusterIP
    ports:
        - name: http
          port: 5601
          targetPort: 5601
          protocol: TCP